# Generated by Django 4.0 on 2022-01-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(default='name of news', max_length=200)),
                ('text_news', models.TextField(default='content of news')),
            ],
            options={
                'verbose_name': 'Addition',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='aki', max_length=20)),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
    ]
