# Generated by Django 4.0 on 2022-01-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_announcement_delete_addition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-publish']},
        ),
    ]
