# Generated by Django 4.0 on 2022-01-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
    ]
