# Generated by Django 4.0 on 2022-01-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_studentclubstitle_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclubstitle',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
