# Generated by Django 4.0 on 2022-01-04 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_about_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubs_about_description', models.TextField(max_length=500, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
