# Generated by Django 4.0 on 2022-01-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_clubs_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs_about',
            new_name='ClubsAbout',
        ),
    ]
