# Generated by Django 4.0 on 2022-01-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_rename_clubs_about_clubsabout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'about university'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name_plural': 'announcements'},
        ),
        migrations.AlterModelOptions(
            name='clubsabout',
            options={'verbose_name_plural': 'description of clubs'},
        ),
        migrations.AlterModelOptions(
            name='studentclubstitle',
            options={'verbose_name_plural': 'description of student clubs'},
        ),
        migrations.AlterField(
            model_name='clubsabout',
            name='clubs_about_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
