# Generated by Django 4.0 on 2022-01-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_about_options_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubsAbout',
        ),
    ]
